(aas-build:compile-load-files
 '(
   "package"
   "base"
   "adj-list"
   "bfs"
   "dfs"
   "priority-queue"
   "single-source"
   "dijkstra"
   "bellman-ford"
   "priority-queue-test"
   "test.lisp"))
